title       = "thegradient"
baseURL     = "https://thegradient-cli.tamnd.com/"
description = "A command line for thegradient."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/thegradient-cli"
